name: React CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # You can keep multiple Node.js versions

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Set up Node.js and npm caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install project dependencies
      - run: npm ci

      # Run your build command (usually creates a production-ready build in React)
      - run: npm run build --if-present

      # Optionally, run tests (if you have any)
      - run: npm test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment happens after the build job completes
    steps:
      # Checkout repository again for the deployment step
      - uses: actions/checkout@v4

      # Set up GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # React build output directory
